pradosoft/prado

- framework/Data/DataGateway/TSqlCriteria.php
- framework/Web/Javascripts/source/prado/validator/validation3.js
Issue 542: the function validate return true in any case but should return false if this.isValid equal false.
Issue 549: the condition of the criteria cannot be reseted when empty value
> Issue 542 and 549

- HISTORY
- framework/Exceptions/messages/messages.txt
- framework/Web/Javascripts/css-packages.php
- framework/Web/Javascripts/packages.php
- framework/Web/UI/TClientScriptManager.php
- framework/Web/UI/WebControls/TStyleSheet.php
> Added TClientStyleSheet::PradoStyles

- HISTORY
- framework/Web/UI/ActiveControls/TActiveFileUpload.php
- framework/Web/UI/WebControls/TFileUpload.php
Fix #581 using the second proposed method
> Fix tracking of localfile path in TActiveFileUpload

- framework/Web/UI/WebControls/TMetaTag.php
Add [charset](https://www.w3.org/TR/2010/WD-html-markup-20101019/meta.charset.html) attribute to meta and disable content for this attribute
> Add html5 charset attribute to meta

- framework/Data/Common/Pgsql/TPgsqlMetaData.php
Hello the PRADO Group,
According to the feature request #708 I have prepared pull request with proposed change. This change adds support for PostgreSQL 12 to the PRADO framework.
Thank you in advance for applying this change.
Best regards,
Marcin Haba (gani)
> Add support for PostgreSQL 12 #708

- HISTORY.md
- framework/Web/Javascripts/source/prado/activecontrols/ajax3.js
- phpunit.xml
- tests/FunctionalTests/issues/protected/pages/Issue724.page
- tests/FunctionalTests/issues/protected/pages/Issue724.php
- tests/FunctionalTests/issues/tests/Issue724TestCase.php
Applied patch from #724 and created a testcase
> Ajax queue improvements

- framework/Util/TCallChain.php
- tests/unit/Util/TCallChainTest.php
> #846 Corrects ordering of TCallChain (#850)

- framework/TComponent.php
- framework/Util/IBaseBehavior.php
- framework/Util/IBehavior.php
- framework/Util/TBehavior.php
- framework/Util/TBehaviorsModule.php
- framework/Util/TClassBehavior.php
- tests/unit/Util/TBehaviorsModuleTest.php
> #824 Fixed: behaviors are initiated with configuration data

- tests/unit/Util/TSimpleDateFormatterTest.php
This is a very time sensitive change request.    any commits to any branches today will fail without this.  Only on months with 31 days, on the last day will this unit test always fail.
> #856 corrected TSimpleDateFormatterTest unit, the 09 month => 8

- framework/Exceptions/messages/messages-fr.txt
- framework/Exceptions/messages/messages-id.txt
- framework/Exceptions/messages/messages-zh.txt
- framework/Exceptions/messages/messages.txt
- framework/Web/UI/WebControls/TSafeHtml.php
- framework/Web/UI/WebControls/TTextBox.php
> Define the html purifier cache in the runtime directory

- framework/Prado.php
> Make Prado::using able to autoload traits defined as prado3 namespaces

- framework/Exceptions/messages/messages.txt
I got very tired last night and forgot this one little edit before submitting the merge.  Easy enough to fix.
> #861 Added the exception to the messages for ensureHexColor 

- framework/Collections/TListItemCollection.php
This accidentally made its way into the merge.
> #889 Removed the return type on TListItemCollection::insertAt

- framework/Collections/TPriorityCollectionTrait.php
- framework/Collections/TWeakCallableCollection.php
- tests/unit/Collections/TWeakCallableCollectionTest.php
with comprehensive unit test.
This has been scrubbed to scrub only once when it scrubs, and it scrubs on almost everything.
"and It's not so much a Ding as a Bub, because the zinged get subbed upon being nothing."  - Fake Dr. Seuss.
> #848 WeakCallableCollection - Scrubs invalid WeakReferences

- framework/Collections/TMap.php
- framework/Collections/TPriorityCollectionTrait.php
- framework/Collections/TPriorityItemTrait.php
- framework/Collections/TPriorityList.php
- framework/Collections/TPriorityMap.php
- framework/Collections/TWeakCallableCollection.php
- framework/classes.php
- tests/unit/Collections/TListTest.php
- tests/unit/Collections/TMapTest.php
- tests/unit/Collections/TPriorityListTest.php
- tests/unit/Collections/TPriorityMapTest.php
- tests/unit/Collections/TWeakCallableCollectionTest.php
> #908 Adding items with [] adds by new index in TMap, TPriorityMap preserves numeric keys

- framework/Web/UI/TTemplateManager.php
This is a very minor php doc update to the new methods in TTemplateManager to flag them as 4.2.3
> Added @ since to the new TTemplateManager methods

- framework/Collections/TPriorityMap.php
- tests/unit/Collections/TPriorityMapTest.php
> TPriorityMap exposing the getNextIntegerKey

- framework/Prado.php
- framework/TComponent.php
- tests/unit/PradoBaseTest.php
Someone suggested this change and its a good idea.
> Updated the name from Prado::Method_Exists to Method_Accessible

- tests/unit/TComponentTest.php
All is fine.  just forgot this unit test.
> Unit Test for behavior handlers receiving behavior priority

- framework/Security/Permissions/TPermissionsBehavior.php
- framework/Security/Permissions/TPermissionsConfigurationBehavior.php
- framework/Security/Permissions/TPermissionsManager.php
- framework/Security/Permissions/TPermissionsManagerPropertyTrait.php
- framework/Security/Permissions/TUserPermissionsBehavior.php
- framework/classes.php
- tests/unit/Security/Permissions/TPermissionsManagerTest.php
Also adds to wake up: reset the PermissionsManager
> #954 Permissions Behaviors "manager" property is zappable sleep prop

- framework/Collections/TMap.php
- framework/Data/Common/Mssql/TMssqlCommandBuilder.php
- tests/unit/Collections/TMapTest.php
Removes all of an item from the map
> #958 TMap::removeItem

- framework/Collections/TMap.php
- framework/Collections/TPriorityMap.php
- tests/unit/Collections/TMapTest.php
- tests/unit/Collections/TPriorityMapTest.php
RemoveItem works on the same item with multiple keys.  keyOf should work similarly.
Default is all item, but option for the first.
> #925 Additional keyOf work for multiple keys and the same item.

- framework/Exceptions/messages/messages.txt
- framework/Util/TVarDumper.php
Updates the PRADO TVarDumper with updates that the Yii2 VarDumper has
> TVarDumper backport update
