pradosoft/prado

framework/Data/DataGateway/TSqlCriteria.php

According to the issu 549, there are an error in the new commit. It must not be
if(empty($value)) {
// reset the condition
$this->_condition = '';
return;
}
but:
if(empty($value)) {
// reset the condition
$this->_condition = null;
return;
}

reset the condition when empty

---

HISTORY
framework/PradoBase.php

Prado emits a fatal error when its autoloader fails to load a class.
This is a pain when using 3rd party libraries that implements their own autoloader, since Prado breaks the autoloading chain avoiding other libraries from autoloading their classes.
Also, any code using class_exists() without setting to false the “autoload” parameter is prone to cause fatal error.
Now that Prado registers a shutdown function, it’s able to handle this situation without the need of a fatal error, so just remove it.
Fix #582

Remove fatal error on autoload fail

---

HISTORY
framework/Web/Javascripts/source/prado/activecontrols/ajax3.js

Prado currently uses jQuery's [serialize](https://api.jquery.com/serialize/) function on the <form> object to collect <input> values and send them to php on postbacks and callbacks.
We recently introduced [TJuiDialog](http://www.pradoframework.net/demos/quickstart/?page=JuiControls.Widgets#TJuiDialog) based on jQueryUI's dialog control. To avoid positioning problems, the control removes it contents from the document and appends them back as a direct child of <body>.
Here it comes bug #588: any control inside TJuiDialog is no more child of the <form>, so its value won't be sent to php anymore. The simplest fixes are:
1. force the TJuiDialog back inside the form (possibly risky as it could break the layout);
2. serialize any input on the page even if it's not inside the <form> (breaks …

Serialize all inputs to catch inputs outside <form>

---

HISTORY.md
UPGRADE.md
framework/Web/Javascripts/source/prado/validator/validation3.js
framework/Web/UI/WebControls/TBaseValidator.php
framework/Web/UI/WebControls/TListControl.php

Client side validators needs special handling to extract values from some special controls (eg. lists). After the "big namespace update" this code worked in our tests, but failed to correctly detect subclasses of these special controls.
This PR reworks the code in order to fix the issue and clean up  a bit the mess.
Also, an additional change removes the usage of `PromptText` as a fallback for `PromptValue` if not specified. This was introduced for browser support, but it looks like modern browsers can handle empty values just fine, while this behavior tricks our validators.

Fix validators on some subclasses; Fix #683

---

framework/Security/TSecurityManager.php

An incorrect private property in the existence check for the crypt algorithm has been used which always leads to an error when setting the algorithm.

Fix usage of incorrect private property

---

framework/TApplicationComponent.php
framework/Util/Behaviors/TMapRouteBehavior.php
framework/Web/Javascripts/source/prado/prado.js
framework/Web/UI/TSkinTemplate.php
framework/Web/UI/TTemplate.php
framework/Web/UI/TTheme.php
framework/classes.php
tests/unit/Util/Behaviors/TMapRouteBehaviorTest.php
tests/unit/Web/UI/TTemplateTest.php
tests/unit/Web/UI/TUSkinTemplateTest.php

This is a general update to
- TMapRouteBehavior- changes the public variable to a private variable with getter/setter. It adds the method to the owner but that shouldn't be an issue.
- Adds a Javascript extension to Number and String adding the method px() that adds "px' to the end of a number or string.  The string checks if px is at the end and if not, adds it.  This should make conversion from numbers and strings to css pixel sizes more standardized and uniform.
- TApplicationComponent adds caching the fx events in the application cache when in normal or performance mode.
- TTemplate adds attribute validation property.
- TSkinTemplate sets TTemplate attribute validation to false
- TThemes use TSkinTemplate rather than TTemplate for skins #737

incremental update Corrections, speedups-caching, and Themes using TSkinTemplate without validation

---

framework/Web/UI/ActiveControls/TCallbackResponseWriter.php

Hello, I found this bug when I try to migrate in master version with PHP 8.1 .
uniqid don't allow null at parameter anymore...

Adapt for compatibility with PHP 8.1

---

framework/Data/DataGateway/TSqlCriteria.php

The phpdoc comment was not correct. the functions can accept array an ArrayAccess but only Array access as defined on the comment. So my IDE inform me than it's not correct when I pass an array in the functions

Update TSqlCriteria.php for fix phpdoc

---

framework/Shell/TShellApplication.php
framework/Shell/TShellLoginBehavior.php
framework/Shell/TShellWriter.php
framework/Util/Behaviors/TBehaviorParameterLoader.php
framework/Util/Cron/TCronModule.php
framework/Util/Cron/TCronTask.php
framework/Util/Cron/TDbCronModule.php
framework/Util/Cron/TShellCronAction.php
framework/Util/Cron/TShellCronLogBehavior.php
framework/Util/Cron/TTimeScheduler.php
framework/Util/TCallChain.php
framework/Web/UI/TTheme.php
tests/unit/Util/Cron/ClearCronTest.php
tests/unit/Util/Cron/TCronModuleTest.php
tests/unit/Util/Cron/TCronTaskTest.php
tests/unit/Util/Cron/TDbCronModuleTest.php
tests/unit/Util/Cron/TShellCronActionTest.php
tests/unit/Util/Cron/TShellCronLogBehaviorTest.php
tests/unit/Util/Cron/TShellDbCronActionTest.php
tests/unit/Util/Cron/TTimeSchedulerTest.php

This fixes the three issues identified in #815.
1) Initializes lastExecTime for cron when loading persistent data from the global state.
1) Initializes lastExecTime for DB Cron on adding and updating (when schedule is changed).
2) Better null nextTriggerTime handling stopped the recurring tasks without a next time.
3) Also removed the Timezone code from TTimeScheduler to correct the erroneous one hour offset.
Also adds better cron shell output when there is no lastexectime (or no runs)
Adds an "@1668165071" unix timestamp format to the TTimeScheduler to reduce computation time for validation, parsing, and next trigger time of one off tasks.
TTimeScheduler regex building is cached.
Corrects a bug in the shell tableWidget column and last column wrapping.
minor documentation update to cron. …

#815 Cron trigger on first run fix, repeat running fix, and removed time zone code

---

framework/Data/DataGateway/TSqlCriteria.php

Hello The PRADO Group,
According to issue #819 I would like to add to the framework support for OFFSET parameter without LIMIT clause. In MySQL OFFSET has to be used together with LIMIT clause, but in PostgreSQL syntax OFFSET can be used without LIMIT.
Thank you in advance for accepting this change.
Best regards,
Marcin Haba (gani)

Add support for OFFSET parameter without LIMIT clause in SQL query for TActiveRecord; fix #819

---

framework/Util/TCallChain.php
tests/unit/Util/TCallChainTest.php

This removes the array reversal in TCallChain.  Call in order; not dependent upon handlers to maintain order
with unit tests

Corrects ordering of TCallChain; with unit test; fix #486

---

framework/Collections/IPriorityProperty.php
framework/Collections/TPriorityList.php
framework/Collections/TPriorityMap.php
framework/Collections/TWeakCallableCollection.php
framework/classes.php
tests/unit/Collections/TPriorityListTest.php
tests/unit/Collections/TPriorityMapTest.php

This is needed for bug fixes to Behaviors in #838
This also abstracts TPriority*::ensurePriority for setting default priority to null values, rounding to precision, and converting to string.
Updates TWeakCallableCollection for IPriorityProperty as well.
With unit tests. much better unit tests for TPriorityMap regarding priorities.

Fixes #847 Adds IPriorityProperty & updates TPriority* to set priority on items

---

framework/Exceptions/messages/messages.txt
framework/Util/TCallChain.php
tests/unit/Util/TCallChainTest.php

TCallChain is a different animal regarding dynamic events than other classes.  As a small utility class, I can't imagine it having its own behaviors for modifying its function.  Those could be identified and accounted for if/when the time comes.

#855 TCallChain throws exception when incorrect dynamic event

---

framework/Collections/IPriorityCapture.php
framework/Collections/IPriorityProperty.php
framework/Collections/TPriorityList.php
framework/Collections/TPriorityMap.php
framework/Collections/TWeakCallableCollection.php
framework/classes.php
tests/unit/Collections/TPriorityListTest.php
tests/unit/Collections/TPriorityMapTest.php

Added IPriorityCapture to capture changes to priority but not set them.  IPriorityProperties is the interface for extending both giving and receive priority.

#847 just IPriorityCapture changes

---

HISTORY.md
UPGRADE.md
framework/Web/THttpRequest.php
framework/Web/THttpRequestResolveMethod.php
framework/classes.php

This new parameter instructs THttpRequest on the behavior used to determine the correct service to be used to handle the request
Fix #868

Implement THttpRequest::ResolveMethod

---

framework/Collections/TList.php
framework/Collections/TMap.php
framework/Collections/TPriorityList.php

The TList and TPriorityList is updated to check contains against -1 rather than being greater than or equal to 0.  This subtle change allows subclasses to override indexOf to work with contains when returning, eg, a string rather than just an index.   This allows implementations to access more contained data than just the primary list.
The TMap needed to be corrected from ?? to array_key_exists as well.

#840 Update TMap, TList, and TPriorityList

---

HISTORY.md
framework/Security/Permissions/TPermissionsBehavior.php
framework/Security/Permissions/TPermissionsConfigurationBehavior.php
framework/Security/Permissions/TPermissionsManager.php
framework/Security/Permissions/TUserPermissionsBehavior.php
tests/unit/Security/Permissions/TPermissionsBehaviorTest.php
tests/unit/Security/Permissions/TPermissionsConfigurationBehaviorTest.php
tests/unit/Security/Permissions/TUserPermissionsBehaviorTest.php

basically, as behaviors, these shouldn't hog the "getManager" name from other behaviors, and it needed to be more specific on its own.

#843 changed PermissionsBehaviors::getManager to getPermissionsManager for specificity

---

HISTORY.md
framework/Data/ActiveRecord/TActiveRecord.php
framework/Data/SqlMap/Statements/TMappedStatement.php
framework/TApplication.php
framework/TComponent.php
framework/Util/Behaviors/TNoUnserializeBehaviorTrait.php
framework/Util/Behaviors/TNoUnserializeClassBehaviorTrait.php
framework/Util/TBehavior.php
framework/Util/TCallChain.php
framework/Web/UI/WebControls/TStyle.php
tests/unit/TComponentTest.php
tests/unit/Util/Behaviors/TNoUnserializeBehaviorTraitTest.php
tests/unit/Util/Behaviors/TNoUnserializeClassBehaviorTraitTest.php

This corrects an error display bug in TApplication::resolvePaths where the path isn't displayed because it is overwritten by the bad value.
This adds TComponent::_clone and __wakeup.  It was necessary to create a function just for calling methods (functions, dynamic events, and global events) on behaviors.  The __clone and __wakeup add dynamic events dyClone and dyWakeUp but they cannot call the object; they must call only the behaviors or weird recursion will happen.
removed check for get_called_class because it was only needed for PHP versions before 7.
Less strict phpdoc type casting in asa.
The events of a TComponent are zapped because they are weak references and must be reconstructed during unserialize anyway.
TBehavior adds __clone to null the owner. it also adds zappable sleep …

#845 Adds behavior support to TComponent on clone and wakeup

---

framework/TPropertyValue.php
tests/unit/TPropertyValueTest.php

This adds support for an array of color [$r, $g, $b] or ['red' => $r, 'green' => $g, 'blue' => $b].  eg. a color can be retrieved by GD and converted into an RGB Hex Color.
Proper documentation and unit tests included.

#861 Added EnsureHexColor support for array type colors

---

framework/Collections/TAttributeCollection.php
framework/Collections/TList.php
framework/Collections/TListItemCollection.php
framework/Collections/TMap.php
framework/Collections/TPagedList.php
framework/Collections/TPriorityList.php
framework/Collections/TPriorityMap.php
framework/Collections/TWeakCallableCollection.php
framework/Web/UI/TControlCollection.php
tests/unit/Collections/TListTest.php
tests/unit/Collections/TPriorityListTest.php

TList and TMap variables and some methods are typed.  subclass methods that could override an input or output are not typed.
The storage is made protected rather than private because some subclasses may need direct access to the storage _d.  TWeakList needs to scrub _d in place without accessor functions.
A few functions were move around to make the files and method locations more symmetric to each other.
_getZappableSleepProps is added to TList, TPriorityList, TPriorityMap, and TWeakCallableCollections
TPriorityList uses its parent _d.  Smaller code can be made for insertAtIndexInPriority as well.  offsetGet is redundant
Regression on existing TList and TMap subclasses are updated
TPriorityListTest unit tests are corrected (not that it did something erroneous)

#889 TList/TMap variable types and minor updates

---

framework/Caching/TDbCache.php
framework/Data/TDbConnection.php
framework/Security/IUserManager.php
framework/Security/TAuthManager.php
framework/Security/TDbUser.php
framework/Security/TDbUserManager.php
framework/Security/TUserManager.php
framework/Shell/TShellLoginBehavior.php
framework/Util/Cron/TShellCronAction.php
tests/unit/Collections/TWeakCallableCollectionTest.php
tests/unit/Data/SqlMap/DataMapper/TPropertyAccessTest.php
tests/unit/Util/Cron/TShellCronLogBehaviorTest.php
tests/unit/Util/Cron/TShellDbCronActionTest.php
tests/unit/Web/TUriTest.php

Due to the upgrade of PRADO to PHP 8.1 and 8.2, today became upgrade day from PHP 8.0.  so then move to 8.1 or 8.2?   how about 8.2...
PHP-CS-Fixer is saying it doesn't support PHP 8.2.  This just may be my install being out of date and needing a `composer update` command.
And there were a few errors that needed fixing:
- removed deprecated callable styles from TWeakCallableCollection unit tests that were failing.
- Some test units failed to declare some variables.
- TPropertyAccess unit test tests for undeclared variables that is deprecated in 8.2; requiring an update.  PHP 8.1 runs the tests, PHP 8.2 fails gracefully without error.
- There was a minor conversion (float => int) error in TShellCronAction regarding display of time.
- Added SensitiveParameter flag to Password parameters in …

#872 Corrections for PHP 8.2: erroneous missing properties in unit tests, type conversion, flagging Password parameters as sensitive

---

framework/Collections/TPriorityCollectionTrait.php
framework/Collections/TPriorityList.php
framework/Collections/TPriorityMap.php
framework/Collections/TWeakCallableCollection.php
framework/Exceptions/messages/messages.txt
framework/classes.php
tests/unit/Collections/TListTest.php
tests/unit/Collections/TMapTest.php
tests/unit/Collections/TPriorityListTest.php
tests/unit/Collections/TPriorityMapTest.php
tests/unit/Collections/TWeakCallableCollectionTest.php
tests/unit/Collections/TWeakListTest.php

This adds the TPriorityCollectionTrait to simply the TPriorityList/Map classes.
TPriorityList is made more efficient in reducing variable/array copying and has better error checking.  This also adds support for copyFrom and MergeWith of TPriorityMap; where the keys are dropped and put in the order given.
TPriorityMap is made more efficient in reducing variable/array copying and add support for copyFrom and MergeWith a TPriorityList where the list index is treated as the key in the map.  List index numbers are the new keys at the specified priority.
TWeakCallableCollection gets two new functions getIterator and toArray to account for changes in the TPriorityList code.
The new traits and classes are added the classes.php list.
Unit tests for the new code.

TPriorityList and TPriorityMap updates for less variable copying and better organization

---

framework/Exceptions/messages/messages-fr.txt
framework/Exceptions/messages/messages-id.txt
framework/Exceptions/messages/messages-zh.txt
framework/Exceptions/messages/messages.txt
framework/TApplication.php
framework/Web/Services/TPageService.php
framework/Web/UI/TTemplateManager.php
framework/Web/UI/TThemeManager.php

the old methods in TPageService were marked deprecated and marked for removal in PRADO 4.3.
one error message wasn't needed any more.  It was deleted.

#829 Moved TThemeManager and TTemplateManager from TPageService to TApplication

---

composer.json
framework/Util/TEscCharsetConverter.php
framework/Util/TUtf8Converter.php
framework/classes.php

```
toUTF8($string, $from, $lang = null)
fromUTF8($string, $to, $lang = null)
```
these functions add the $lang parameter for setting the PHP setLocale(LC_CTYPE, $lang) because various countries/languages have slightly different character sets despite being the same encoding.  eg ASCII has different national standards.
This is the most comprehensive list of ESC character set encodings i was able to find in reasonable time.

#864 TUtfConverter takes language for national localization and TEscCharsetConversion for converting ESC charsets

---

framework/Web/UI/ITemplate.php
framework/Web/UI/JuiControls/TJuiAutoCompleteTemplate.php
framework/Web/UI/JuiControls/TJuiSelectableTemplate.php
framework/Web/UI/JuiControls/TJuiSortableTemplate.php
framework/Web/UI/TTemplateManager.php
framework/Web/UI/WebControls/TWizardNavigationTemplate.php
framework/Web/UI/WebControls/TWizardSideBarListItemTemplate.php
framework/Web/UI/WebControls/TWizardSideBarTemplate.php

With the option of setting a new default template class upon instancing of TTemplateManager.
This change allows a template to be formed upon a designated culture rather than just the web user's culture settings.  this is important for when sending emails to someone with different culture settings.  The template must be formed around the email receiver and not the web user.

#827 TTemplateManager accepts template class and culture

---

framework/TComponent.php

Sorry about not leaving a comment.  This corrects that behaviors that are created are initialized, not just when they have a configuration.

#824 updated the TComponent::instanceBehavior to init

---

HISTORY.md
framework/TApplication.php
framework/TApplicationConfiguration.php
framework/Util/Behaviors/TBehaviorParameterLoader.php
framework/Util/TParameterModule.php
tests/unit/TPropertyValueTest.php
tests/unit/Util/Behaviors/TBehaviorParameterLoaderTest.php

This updates two parts
- TBehaviorParameterLoader needed to stash the $config into the behavior initialization array so it would init with the data properly.
- dyInit is fed its xml parameter node or php array in case it has more complex configuration than just one node or properties.

#824 TBehaviorParameterLoader needs config on Behavior::init, dyInit fed its parameter configuration object

---

HISTORY.md
framework/Exceptions/messages/messages.txt
framework/TComponent.php
framework/Util/Behaviors/TBehaviorParameterLoader.php
framework/Util/IBaseBehavior.php
framework/Util/IBehavior.php
framework/Util/IClassBehavior.php
framework/Util/TBaseBehavior.php
framework/Util/TBehavior.php
framework/Util/TClassBehavior.php
framework/classes.php
tests/unit/TComponentTest.php
tests/unit/Util/Behaviors/TParameterizedBehaviorTest.php
tests/unit/Util/TBaseBehaviorTest.php

This fixes #891, #851, and #838
- TClassBehavior tracks owners with TWeakList
- Attaching IBehavior to Class clones instances for each owner/instance. the standard action was to instance from a class name string or array of class/properties.
- TComponent::__destruct clears the behaviors and event handlers for better garbage collection.
- IBaseBehavior has Enabled flag.  Thus, IClassBehavior has enabled flag.  Simplifies TComponent behavior processing.
- TBaseBehavior records its unique attachment name in the owner.  IClassBehavior can only install on one name across all owners.
- Attaching a behavior over an existing name properly removes the prior behavior.
- TBehavior and TClassBehavior track the behavior enabled status of their owner by dynamic event dyEnableBehaviors and …

4.2.3 General Behaviors Update... 

---

framework/TComponent.php
framework/Util/TBaseBehavior.php
framework/Util/TBehaviorsModule.php
tests/unit/TComponentTest.php

Not much to document here.  Very simple change: a lot of strtolower

#910 TComponent behavior names made case insensitive

---

framework/Prado.php
framework/TComponent.php
tests/unit/Collections/TPriorityMapTest.php
tests/unit/PradoBaseTest.php
tests/unit/TComponentTest.php

There is a large number of test units to make sure that access is proper from all angles: // Test public
External calls parent access Parent property (public, protected, and private)
External calls child access child property.       "
External calls parent access child property.    "
External calls child access parent property.    "
// test protected and private:
Parent calls parent access Parent property (public, protected, and private)
Parent calls child access child property.       "
Parent calls parent access child property.    "
Parent calls child access parent property.    "
child calls parent access Parent property (public, protected, and private)
child calls child access child property.       "
child calls parent access child property.    "
child calls child access parent …

#898 Magic Method access to getter/setter/methods is determined by caller relation to implementation

---

framework/Util/TBitHelper.php

I was going through the TBitReader and found this optimization for more compliant masks.
Technically, this shouldn't even be a problem in the code but I want to use the best mask calculation algorithm as an example for others.   The problem was collision left shifting 1 by the total number of bits is that the shift would push the bit off.
Instead of `(1<<$bits) - 1` it should be `~(-1 << $bits)` as this preserves the masking when $bits = PHP_INT_SIZE * 8

TBitHelper has better masking algorithm

---

framework/Collections/TList.php
framework/Collections/TMap.php
framework/Collections/TPriorityCollectionTrait.php
framework/Collections/TPriorityList.php
framework/Collections/TPriorityMap.php
framework/Collections/TWeakCallableCollection.php
framework/Collections/TWeakList.php
framework/Exceptions/messages/messages.txt
framework/Prado.php
framework/TComponent.php
tests/unit/Collections/TListTest.php
tests/unit/Collections/TMapTest.php
tests/unit/Collections/TPriorityListTest.php
tests/unit/Collections/TPriorityMapTest.php
tests/unit/Collections/TWeakCallableCollectionTest.php
tests/unit/Collections/TWeakListTest.php
tests/unit/PradoBaseTest.php

This resolves the issue of setting TList/TMap::ReadOnly in configuration.  while preserving access control over the property.
This converts TMap and TList Read only into a null and accepts first set and self set.
Regression.
With unit tests.

#898 TList/TMap:: setReadOnly made public, only allow first set & self set

---

framework/Collections/TMap.php
framework/Collections/TPriorityMap.php
tests/unit/Collections/TMapTest.php
tests/unit/Collections/TPriorityMapTest.php

TPriorityMap should not just return the first instance of a value but it should depend on the priority.  higher priorities are first in the map.

#925 TMap::keyOf is added, additional checks on TPriorityMap

---

framework/Exceptions/messages/messages.txt
framework/Util/Math/TRational.php
framework/Util/Math/TURational.php
framework/Util/TBitHelper.php
framework/classes.php
tests/unit/Util/Math/TRationalTest.php
tests/unit/Util/Math/TURationalTest.php

The Mathematical "rational" is an integer numerator divided by an integer denominator.  This is the class providing the functionality around reading, computing, and outputting the rational.
The format for the Rational is, eg,  "21/13" where 21 is the numerator and 13 is the denominator.
The unsigned rational is bound to 0..4294967295; where as the regular rational is signed and bound to [-2147483648..2147483647].
A Rational is found in EXIF and is common in its GPS "directory".  It is found there as two 32 bit integers.
The star method of this class is the Continued Fraction computation to generate the integer numerator and integer denominator from a float, to a specific tolerance.
Updated TBitHelper with specific max, min, unsigned max, and mask for 32 bit and 64 bit integers, when the …

#904 TRational/TURational unit classes Prado\Util\Math

---

framework/Util/Math/TRational.php
tests/unit/Util/Math/TRationalTest.php

Minor update to handle null with unit tests.
null value was missing from offsetExists and offsetUnset.  This makes the handling of null uniform

TRational offsetExists and offsetUnset handles null, unit tests

---

framework/Util/Math/TRational.php
framework/Util/TBitHelper.php
tests/unit/Util/TBitHelperTest.php

float IEEE format INF vs NAN depends on if the mantissa is 0 or not.  Any value of mantissa is NAN and is valid for NAN.  But PHP picks a specific value for NAN that we mimic here as a standard.

TBitHelper:: floatToFpXX Better Compliance to PHP binary format of NAN

---

framework/Util/Cron/TDbCronModule.php
tests/unit/Util/Cron/TDbCronModuleTest.php

The test itself wasn't quite right.  it should sort by asc (false), not descending (true). and ordering by uid (aka entry order) as well.
This should fix the issue.  I think it was spotty when TDBCron executing the test between seconds and the ordering was by time....
Thus when they were all the in the same second, it was ordering by UID correctly on the log

#918 fixing spot DBCron test failure.

---

HISTORY.md
framework/TComponent.php
tests/unit/TComponentTest.php

Unit tests to make sure Closures work.  Minor change to TComponent to support Closures.

#848 TComponent Events support Closures and all callable types (with unit tests)

---

framework/TApplicationComponent.php

"Restoring order to the force." - Not Yoda
presuming scope and data that isn't there can lead to errors.

#940 Correcting the scope of getClassFxEvents::$_classfx

---

framework/Collections/TWeakCallableCollection.php
framework/TEventHandler.php
tests/unit/Collections/TWeakCallableCollectionTest.php
tests/unit/TEventHandlerTest.php

For TEventHandler and TWeakCallableCollection
with unit tests
The TWeakList doesn't WeakReference array objects that implement IWeakRetainable.  This commit makes that behavior consistent in TEventHandler and TWeakCallableCollection.
Not sure what the use case would be for having something respond to an event where it is the only instance in the application, but it is the proper maths.

#939 IWeakRetainable consistency for objects in callable array

---

HISTORY.md
framework/Exceptions/TException.php
framework/Exceptions/TExitException.php
framework/Exceptions/TUserException.php
framework/TApplication.php
framework/classes.php

In TException, when the final parameter is a Throwable, it becomes the $previous Exception of the exception.
Yay for Exception chaining support.
I saw this in a PHP doc comment and then saw it implemented in Yii.  We should have it too.
"back porting?"
This also adds the TUserException designed for display to the end user.

#944 TExitException for graceful exit of application & TException chaining

---

framework/Exceptions/TException.php

When updating TException I accidentally left in an array_shift.
It shouldn't be shifting off the first argument like before.

TException shouldn't be shifting off the first arg

---

framework/Caching/TDbCache.php
framework/TApplicationComponent.php
framework/TApplicationStatePersister.php
tests/unit/Data/SqlMap/Ticket589Test.php

I have been testing the SQL with SqlLite3 and it works.  From what I know, this should work in MySQL and other databases as well, as REPLACE is  (edit: NOT) part of SQL common language.
The update to getClassFxEvents is also a win.  I think it's at least a little faster.
I'm doing further testing on this after a good nights rest.

#940 TApplicationComponent::getClassFxEvents update and TDBCache::setValue uses atomic SQL

---

framework/Collections/TPriorityCollectionTrait.php

#872. moving to PHP8 makes this change required.

#956 Stripping the priority keys for merge/replace, not needed after sorting away

---

framework/Collections/TWeakCallableCollection.php
tests/unit/Collections/TWeakCallableCollectionTest.php
tests/unit/TComponentTest.php

Basically,`Prado::createComponent` only attaches one event handler per event but it should be able to attach multiple handlers to each event.  This requires TWeakCallableCollection to accept and insert an array of handlers rather than just one handler at a time.

#966 TWeakCollection can insert array of handlers. (this first)

---

HISTORY.md
framework/Collections/TPriorityMap.php
framework/TComponent.php
framework/TEventResults.php
tests/unit/TComponentTest.php

There are 5 upgrades to TComponent:
- __destruct ordering is corrected so behaviors are removed before unlisten. this is to properly unwind and reverses the order of __construct.
- raiseEvent can execute the handlers in reverse.  This is needed if the first handlers needs to be executed last for proper priority/importance of the result.   This adds TEventResults::EVENT_REVERSE
- asA is updated so that if a behavior name is not found it, and the $behaviorname is a class/interface, it will look for the first behavior instanceof
- isa is updated to include traits so traits can properly have global class behaviors.
-getBehaviors is updated to return all behaviors of a select class if a class is provided
this also updates and refactors the TComponent unit tests to not use behavior classes as …

TComponent upgrade: raiseEvents in reverse [option], search for behavior by class

---

framework/Data/SqlMap/Statements/TMappedStatement.php

- The creation of a TActiveRecord as a resultClass of a SqlMap did not work because of the detection of the presence of the TActiveRecord class. The class namespace was missing from the string.
- The result was an unloaded object (recordState=0) that could not be saved. Saving triggered a duplicate key error by SQL.

TMappedStatement fix calling TActiveRecord::createRecord

---

framework/TComponent.php

Bug: When the expression in component template  is invalid eval() throw a ParseError or Error , and TErrorHandler cannot determine the file or line of the error.
So we should use \Throwable instead of \Exception to catch all possible errors, including ParseError and Error.
Because in PHP 7 and later, ParseError and Error  implement the \Throwable interface and are not subclasses of \Exception.
Examples: 
<com:TButton Text="Click me" OnClick="buttonClicked" Visible="<%= undefinedFunction() %>" /> <com:TButton Text="Click me" OnClick="buttonClicked" Visible="<%= parse,error%>" />

Replace Exception by Throwable to catch eval ParseError and Error.

---

framework/Web/THttpRequest.php
framework/Web/TUrlManager.php

Recently I had to move some webapps from Apache to Nginx.
While apps working in the main domain folder (eg. www.test.com/) works fine, apps running in a subfolder (eg. www.test.com/app/)  has problems in determining the requested page when `THttpRequest` 's `UrlFormat` is set to `Path` or `HiddenPath`.
This PR contains 2 changes.
The first one adds some fallbacks for determining the requested page path (pathInfo) when the app is using `Path` or `HiddenPath` url formats.
The second change adds a urldecode() call to request parameters when the app is using `Path` or `HiddenPath` url formats. This is meant to fix a niche problem when using array parameters, aka "repeated parameters" from [rfc1738](https://datatracker.ietf.org/doc/html/rfc1738), eg: …

Nginx fixes

---

framework/Data/ActiveRecord/TActiveRecordGateway.php
framework/Data/Common/Mssql/TMssqlMetaData.php
framework/Exceptions/TPhpErrorException.php
framework/Exceptions/messages/messages.txt
framework/Web/THttpSession.php
framework/Web/THttpSessionCookieMode.php
framework/Web/THttpSessionHandler.php
framework/classes.php
tests/unit/Util/TSignalsDispatcherTest.php
tests/unit/Web/THttpSessionTest.php

1. Add THttpSessionhandler to avoid use of deprecated session_set_save_handler() ctor
2. Also deprecated THttpSessionCookieMode(s) that enables usage of session IDs in the url
See https://www.php.net/manual/en/migration84.deprecated.php#migration84.deprecated.session
Added minor fixes to accomodate phpstan and php-cs-fixer and get a green build

THttpSession deprecation updates
